import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import Loading from "./loading";
import Providers from "./redux/provider";
import { SideBar } from "./layouts/sideBar";
import { NavBar } from "./layouts/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<Loading />}>
          <Providers>
            <ToastContainer />

            <div>
              <NavBar />
              {children}
            </div>
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
